### PR TITLE
YubiKey PIN input

### PR DESCRIPTION
**Pull request by basvandriel**
This pull request lets the user provide a PIN code for the selected key and removes the need for providing it in the environment variables.

selectkey

### CODE REVIEW

**Comment by basvandriel** [comment]
Before merging this, we should consider if we want to keep the resetting functionality. On the `CreateRSAKeysPage` page, the `ykman piv reset --force` command is called. This fails on my machine because I don't have the `ykman` executeable, but wouldn't this cause to much confusion for the end user?

**Comment by ricklambrechts** [comment]
Yes that is needed to reset the YubiKey and for us to drop the old PIV keys and certificates.

https://support.yubico.com/hc/en-us/articles/360013645480-Resetting-the-Smart-Card-PIV-Application-on-Your-YubiKey

**Comment by basvandriel** [comment]
> Yes that is needed to reset the YubiKey and for us to drop the old PIV keys and certificates.
> 
> https://support.yubico.com/hc/en-us/articles/360013645480-Resetting-the-Smart-Card-PIV-Application-on-Your-YubiKey

Do we need to reset everything? Can't we just reset the configuration and stored certificates?

**Comment by basvandriel** [comment]
related to https://github.com/minvws/nl-uzipoc-yubisign/issues/49

**Comment by basvandriel** [comment]
Decided with the team to let this pull request stay in draft after we get more information about https://github.com/minvws/nl-uzipoc-yubisign/pull/50.

**Comment by basvandriel** [comment]
Decided to not use this feature currently.

**Pull request closed without merging**
